### ISSUE TITLE
Python Input can't accept an array of Inputs

### ISSUE THREAD

**Issue by mohsin-code** [mohsin-code/OOP-Course#1]
In Lab Report 2/Python/Task3.py 

Link: <a href="https://github.com/mohsin-code/OOP-Course/blob/master/Lab%20Report%202/Python/Task3.py">Task 3</a>

I need to somehow accept 50 inputs from the user separated by space. Input separated by Enter had worked out but I need Input separated by spaces.

**Comment by Amirkhan9439** [comment]
> In Lab Report 2/Python/Task3.py
> 
> Link: [Task 3](https://github.com/mohsin-code/OOP-Course/blob/master/Lab%20Report%202/Python/Task3.py)
> 
> I need to somehow accept 50 inputs from the user separated by space. Input separated by Enter had worked out but I need Input separated by spaces.

You can store user's input in a string and then use the split function on string with delimiter being space (' ').  Try this out

str = input("Enter a string: ")  # lets say user input is "Amir studies at UET"
arr = str.split(' ')
print(arr[1]) //arr[1] will store the word studies

the split(delimiter) function splits the string into array around the delimiter.

**Comment by mohsin-code** [comment]
Issue solved: 5e5ee1fd1c117845143830510fa1305562561a9f

Thank you for the help Amir
