### ISSUE TITLE
Runtime Error: Incorrect Results

### ISSUE THREAD

**Issue by mohsin-code** [mohsin-code/OOP-Course#2]
Value of radius is fine on Circle class call.
Value of radius zeros out when I call the cylinder subclass with a Circle Object as its parameter.

https://github.com/mohsin-code/OOP-Course/blob/6f21603058853a18b04d4f90b3374849617416d8/Lab%20Report%205/C%2B%2B/Task1.cpp#L137

![image](https://user-images.githubusercontent.com/59390499/103021423-ec1be380-456b-11eb-8ab0-990a95a6cd0b.png)

**Comment by mohsin-code** [comment]
@AbdulMajid1m1 
Parent of class Cylinder is changed into Point: 2b06cbe3fe7e84fec27828c269a2fe5758810ffa

Now I cant access the variable radius in Cylinder Class.

![image](https://user-images.githubusercontent.com/59390499/103036188-fc8f8680-458a-11eb-8d50-e37976cc68ee.png)

Should I define a new one inside Cylinder Class?

**Comment by Amirkhan9439** [comment]
> Value of radius is fine on Circle class call.
> Value of radius zeros out when I call the cylinder subclass with a Circle Object as its parameter.
> 
> https://github.com/mohsin-code/OOP-Course/blob/6f21603058853a18b04d4f90b3374849617416d8/Lab%20Report%205/C%2B%2B/Task1.cpp#L137
> 
> ![image](https://user-images.githubusercontent.com/59390499/103021423-ec1be380-456b-11eb-8ab0-990a95a6cd0b.png)

Mohsin on line 110, of your code, you are not initilizing the radius that is inherited by cylinder class from the circle. So when you instantiate the cylinder class, it calls the no aurgument constructor of circle class that sets the radius to 0. Try changing line 110 to this (see bellow) and check result.
Cylinder::Cylinder(float h, Circle c): Circle(c.getrRadius(), 0, 0), height(h){}

**Comment by mohsin-code** [comment]
Issue solved with c4d535d734fcb2796758e178c8966d2bbf0b3cf2

Thanks Amir.
