### ISSUE TITLE
Runtime Error: Output shows only single char

### ISSUE THREAD

**Issue by mohsin-code** [mohsin-code/OOP-Course#3]
Input accepts string literals but when I try to display them it output a single character.

![image](https://user-images.githubusercontent.com/59390499/103150994-a7768f00-479b-11eb-9c03-8135ed63553c.png)

I think error seems to be in this constructor:

https://github.com/mohsin-code/OOP-Course/blob/fa4312a49527eba85f631a238a580cfa0e63d9d4/Lab%20Report%204/C%2B%2B/Task1.cpp#L14-L18

**Comment by Amirkhan9439** [comment]
> Input accepts string literals but when I try to display them it output a single character.
> 
> ![image](https://user-images.githubusercontent.com/59390499/103150994-a7768f00-479b-11eb-9c03-8135ed63553c.png)
> 
> I think error seems to be in this constructor:
> 
> https://github.com/mohsin-code/OOP-Course/blob/fa4312a49527eba85f631a238a580cfa0e63d9d4/Lab%20Report%204/C%2B%2B/Task1.cpp#L14-L18

Mohsin your are dereferencing the character pointer while printing on line 63 [https://github.com/mohsin-code/OOP-Course/blob/fa4312a49527eba85f631a238a580cfa0e63d9d4/Lab%20Report%204/C%2B%2B/Task1.cpp#L63]. Consider changing it to cout<<"\nDetails:\nName: "<<name<<endl; and line 64 to cout<<"Enter department: "<<department<<endl;
Remember that when we dereference a pointer, only the value at that address is returned. If cout is passed address of a character, then it will keep printing all succeeding characters until it encounters a null character.

**Comment by Amirkhan9439** [comment]
> > Input accepts string literals but when I try to display them it output a single character.
> > ![image](https://user-images.githubusercontent.com/59390499/103150994-a7768f00-479b-11eb-9c03-8135ed63553c.png)
> > I think error seems to be in this constructor:
> > https://github.com/mohsin-code/OOP-Course/blob/fa4312a49527eba85f631a238a580cfa0e63d9d4/Lab%20Report%204/C%2B%2B/Task1.cpp#L14-L18
> 
> Mohsin your are dereferencing the character pointer while printing on line 63 [https://github.com/mohsin-code/OOP-Course/blob/fa4312a49527eba85f631a238a580cfa0e63d9d4/Lab%20Report%204/C%2B%2B/Task1.cpp#L63 63]. Consider changing it to cout<<"\nDetails:\nName: "<<name<<endl; and line 64 to cout<<"Enter department: "<<department<<endl;
> Remember that when we dereference a pointer, only the value at that address is returned. If cout is passed address of a character, then it will keep printing all succeeding characters until it encounters a null character.
